# Generated by Django 5.2.3 on 2025-06-25 10:10

from django.db import migrations


def migrate_profiles_data(apps, schema_editor):
    """
    Copie les données de l'ancien modèle Profile (oc_lettings_site.Profile)
    vers le nouveau (profiles.Profile).
    """
    try:
        # Try to get the old model from the historical state of the application
        OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        # If the old app or template has already been deleted,
        # there is nothing to migrate.
        return

    NewProfile = apps.get_model('profiles', 'Profile')

    # Transfer each profile one by one
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        # Depends on the initial migration of the old application
        # to ensure that the source table exists.
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        # Run our data migration function
        migrations.RunPython(migrate_profiles_data),
    ]
