# Configuration file for Read the Docs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for more information.

# Required
version: 2

# Define the operating system, Python version, and tools
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

# Build the documentation with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Declare the Python dependencies required to build the documentation
python:
   install:
   - requirements: requirements.txt