# Generated by Django 5.2.3 on 2025-06-25 10:29

from django.db import migrations


def migrate_lettings_data(apps, schema_editor):
    """
    Copies data from the old Address and Letting models 
    (oc_lettings_site.Address, oc_lettings_site.Letting)
    to the new ones (lettings.Address, lettings.Letting).
    """
    try:
        OldAddress = apps.get_model('oc_lettings_site', 'Address')
        OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    except LookupError:
        # The old app or models might have been removed.
        return

    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')

    # Use a dictionary to map old address IDs to new address objects
    address_map = {}

    for old_address in OldAddress.objects.all():
        new_address = NewAddress.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
        address_map[old_address.id] = new_address

    for old_letting in OldLetting.objects.all():
        # Retrieve the new address object from our map
        new_address_instance = address_map.get(old_letting.address_id)
        if new_address_instance:
            NewLetting.objects.create(
                title=old_letting.title,
                address=new_address_instance
            )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_lettings_data),
    ]
