name: CI-CD Pipeline for Orange County Lettings

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: [ "**" ] # Runs on all branches
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This job runs the tests and linter
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Sets up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs linter (flake8)
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. Runs tests with pytest and checks coverage
      - name: Test with pytest
        run: |
          pytest --cov=. --cov-report=xml
          coverage report --fail-under=80